<?php
/**
 * Import a CSV tweet list
 *
 * Import tweets from an archive as generated by Twitter
 *
 * Usage :
 *   - Import your tweets with the plugin. The plugin will import only the 3200 most recent tweets.
 *   - Download your archive from Twitter, open the tweets.csv file (delete first 3200 most recent tweets to speed up things)
 *   - put tweets.csv into the plugin directory
 *   - run this file with PHP on the command line
 */

if( php_sapi_name() !== 'cli' ) {
    die("Meant to be run from command line");
}

function find_wordpress_base_path() {
    $dir = dirname(__FILE__);
    do {
        //it is possible to check for other files here
        if( file_exists($dir."/wp-config.php") ) {
            return $dir;
        }
    } while( $dir = realpath("$dir/..") );
    return null;
}

define( 'BASE_PATH', find_wordpress_base_path()."/" );
define('WP_USE_THEMES', false);
global $wp, $wp_query, $wp_the_query, $wp_rewrite, $wp_did_header;

require(BASE_PATH . 'wp-load.php');
require(BASE_PATH . "wp-admin" . '/includes/image.php');
require(BASE_PATH . "wp-admin" . '/includes/file.php');
require(BASE_PATH . "wp-admin" . '/includes/media.php');

ozh_ta_require( 'import.php' );
ozh_ta_require( 'option-page.php' );


/*****************************************************************************/

/**
 * Get CSV file name, die if not found
 *
 * @param  string $file  CSV file name (defaults to 'tweets.csv')
 * @return string        Full path to file (or die if not found)
 */
function oti_get_file( $file = 'tweets.csv' ) {
    $file = str_replace( '\\', '/', dirname( __FILE__ ) . '/tweets.csv' );
    if( !file_exists( $file ) ) {
        wp_die( 'Tweet file not found. Put it in the same directory as wp-load.php' );
    }
    
    return $file;
}
 
/**
 * Read a CSV file, process 1st field of each row by batch of defined size
 *
 * @param  string $file   path to file
 * @param  int    $start  first line to process, ignoring all those before
 * @return unknown
 */
function oti_process_file( $file, $start ) {
    $handle = fopen( $file, "r" );
    
    // Always ignore header
    $ignore = fgetcsv( $handle, 30, "," );

    $ignore = $count = 0;
    $finished = false;
    $ok = true;
    
    while ( $count < OZH_TA_BATCH && $data = fgetcsv( $handle, 30, "," )) {
        // Make sure we're reading an actual comma separated line starting with a tweet ID, and not the sequel of a multiline cell
        $id = $data[0];
        if( preg_match( '/^\d+$/', $id ) ) {
            
            // Resume to whished position, ignore lines till line number $start
            if( $ignore++ < ( $start - 1 ) ) {
                continue;
            }
            
            // Now we can start processing each line during next batch
            // Here: not much error checking. Assuming false will be either rate limit exceeded, or Twitter down
	    $import = ozh_ta_import_single_tweet( $id );
            if( $import === false ) {
                $ok = false;
		break;
            }
	    else {
            	$count++;
	    }
            
        }
    }
    
    if( $count < OZH_TA_BATCH && $ok ) {
        $finished = true;
    }
    
    return array( 'ok' => $ok, 'count' => $count, 'finished' => $finished, 'array' => $import );
}

$start = 0;

while (!$import['finished']) {
    echo "/";
	
    // Import
    $import = oti_process_file( oti_get_file(), $start );
    $start += $import['count'];

    if ($import['count'] == 15) { 
	echo $import['count']; 
        sleep(1);
    }
    else {
	echo $import['count'] . " !";
        sleep(120);
    }
}

global $ozh_ta;

// Update real last_tweet_id_inserted, stats, & reset API paging
$ozh_ta['twitter_stats']['link_count'] = $wpdb->get_var( "SELECT COUNT(ID) FROM `$wpdb->posts` WHERE `post_type` = 'post' AND `post_status` = 'publish' AND `post_content` LIKE '%class=\"link%'" );
$ozh_ta['twitter_stats']['replies'] = $wpdb->get_row( "SELECT COUNT( DISTINCT `meta_value`) as unique_names, COUNT( `meta_value`) as total FROM `$wpdb->postmeta` WHERE `meta_key` = 'ozh_ta_reply_to_name'", ARRAY_A );
$ozh_ta['twitter_stats']['total_archived'] = $wpdb->get_var( "SELECT COUNT(`meta_key`) FROM `$wpdb->postmeta` WHERE `meta_key` = 'ozh_ta_id'" );
update_option( 'ozh_ta', $ozh_ta );

echo 'Finished importing tweets!.';
